In [1]:
import numpy as np 
import pandas as pd 


In [2]:
from sklearn.impute import SimpleImputer

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day28-column-transformer/covid_toy.csv')

In [6]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
df.shape

(100, 6)

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [13]:
## in our data set 
# gender and the city is the nominal data so we have to use OneHotEncoding 
# cough is the ordinal data so we have to use the ordinal categorical data so we have to use the ordinal encoding 
# for the has_covid column we have to use the label encoding as it is the target column in our data set 

In [14]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [17]:
X_train

age  gender  fever   cough       city
97   20  Female  101.0    Mild  Bangalore
5    84  Female    NaN    Mild  Bangalore
1    27    Male  100.0    Mild      Delhi
19   42  Female    NaN  Strong  Bangalore
95   12  Female  104.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
25   23    Male    NaN    Mild     Mumbai
11   65  Female   98.0    Mild     Mumbai
16   69  Female  103.0    Mild    Kolkata
82   24    Male   98.0    Mild    Kolkata
48   66    Male   99.0  Strong  Bangalore

[80 rows x 5 columns]

## Aam Zindaghi 

In [19]:
# adding the simple imputer to the fever column 
si = SimpleImputer()

In [20]:
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data 
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [21]:
X_train_fever

array([[101.],
       [101.],
       [100.],
       [101.],
       [104.],
       [ 98.],
       [101.],
       [100.],
       [104.],
       [ 99.],
       [ 99.],
       [100.],
       [ 99.],
       [ 98.],
       [102.],
       [101.],
       [104.],
       [101.],
       [ 99.],
       [101.],
       [100.],
       [101.],
       [102.],
       [104.],
       [101.],
       [ 99.],
       [102.],
       [ 99.],
       [102.],
       [102.],
       [101.],
       [103.],
       [104.],
       [101.],
       [101.],
       [101.],
       [104.],
       [101.],
       [101.],
       [103.],
       [100.],
       [100.],
       [101.],
       [103.],
       [104.],
       [104.],
       [100.],
       [102.],
       [101.],
       [ 98.],
       [104.],
       [100.],
       [101.],
       [100.],
       [ 98.],
       [ 98.],
       [102.],
       [100.],
       [101.],
       [ 98.],
       [100.],
       [104.],
       [103.],
       [104.],
       [101.],
       [101.],
       [10

In [22]:
X_test_fever

array([[100.],
       [102.],
       [ 99.],
       [ 98.],
       [101.],
       [103.],
       [ 98.],
       [103.],
       [101.],
       [104.],
       [ 99.],
       [ 98.],
       [ 98.],
       [100.],
       [103.],
       [101.],
       [ 98.],
       [ 98.],
       [ 98.],
       [104.]])

In [24]:
# OedinalEncoding  ->  cough 
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape


(80, 1)

In [28]:
# OneHotEncoding -> gender , city 

ohe = OneHotEncoder(drop='first',sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also for the test data 

X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [32]:
# Extracting Age 

X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values 

# also the test data 
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values 
X_train_age.shape

(80, 1)

In [33]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough), axis=1)

# also for the test data 
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough), axis=1)

X_train_transformed.shape

(80, 7)

In [34]:
X_train_transformed

array([[ 20., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 84., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 42., 101.,   0.,   0.,   0.,   0.,   1.],
       [ 12., 104.,   0.,   0.,   0.,   0.,   0.],
       [  5.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 81., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 10., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 44., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 72.,  99.,   1.,   0.,   0.,   0.,   0.],
       [ 49.,  99.,   0.,   0.,   0.,   0.,   1.],
       [ 80., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 14.,  99.,   0.,   0.,   0.,   1.,   0.],
       [ 10.,  98.,   0.,   0.,   1.,   0.,   1.],
       [ 82., 102.,   0.,   0.,   1.,   0.,   1.],
       [ 42., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 51., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 38., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 22.,  99.,   0.,   0.,   0.,   0.,   0.],
       [ 79., 101.,   1.,   0.,

In [35]:
X_test_transformed

array([[ 47., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 74., 102.,   1.,   0.,   0.,   1.,   0.],
       [ 65.,  99.,   1.,   1.,   0.,   0.,   0.],
       [ 64.,  98.,   0.,   0.,   0.,   0.,   0.],
       [ 64., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 73., 103.,   0.,   1.,   0.,   0.,   0.],
       [ 73.,  98.,   1.,   0.,   0.,   0.,   0.],
       [ 60., 103.,   1.,   0.,   1.,   0.,   0.],
       [ 83., 101.,   0.,   0.,   1.,   0.,   0.],
       [ 18., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 25.,  99.,   0.,   0.,   1.,   0.,   1.],
       [ 12.,  98.,   1.,   0.,   0.,   0.,   1.],
       [ 83.,  98.,   1.,   1.,   0.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 46., 103.,   1.,   0.,   0.,   0.,   1.],
       [ 49., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 80.,  98.,   0.,   1.,   0.,   0.,   0.],
       [ 71.,  98.,   0.,   0.,   1.,   0.,   1.],
       [ 34.,  98.,   1.,   0.,   1.,   0.,   1.],
       [ 56., 104.,   0.,   0.,

## ye he mentos Zindagi 

In [36]:
from sklearn.compose import ColumnTransformer

In [37]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']), 
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [38]:
transformer.fit_transform(X_train)

array([[101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  72.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  14.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   1.,   1.,   0.,

In [39]:
transformer.fit_transform(X_train).shape

(80, 7)

In [40]:
transformer.transform(X_test).shape

(20, 7)