In [9]:
import pickle
import numpy as np 


In [10]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [17]:
# Assume user imput 

# Pclass/gender/age/sibsp/Fare/Embarked 
test_input = np.array([2, 'female', 31.0, 0, 0, 10.5, 'S'],dtype= object).reshape(1,7)

In [18]:


# Convert test input to DataFrame with correct column names
# test_df = pd.DataFrame(test_input, columns=['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'])


In [19]:
test_input

array([[2, 'female', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [20]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))




c:\Users\santo\OneDrive\Desktop\COESIS30  DAY CHALLANGE\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [21]:
test_input_sex

array([[1., 0.]])

In [16]:
ohe_sex.categories_


[array(['female', 'male'], dtype=object)]

In [22]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [23]:
test_input_age = test_input[:,2].reshape(1,1)

In [24]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [25]:
test_input_transformed.shape

(1, 10)

In [26]:
clf.predict(test_input_transformed)

array([1])

##   array([1])     
##   the 1 represent that the passenger survived the ship crash 